name: Build and Publish

on:
   push:
   pull_request:
   workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [ '2.12.15', '2.13.8' ]
        spark: [ '3.2.4', '3.3.3', '3.4.1', '3.5.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Build and Test
        env:
          JOOM_CLOUD_TOKEN: ${{ secrets.JOOM_CLOUD_TOKEN }}
        run: echo $JOOM_CLOUD_TOKEN
